services:
  s3-ui:
    container_name: to-do-list
    image: to-do-list:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    environment:
      APP_ADDR: ":8080"
      MONITOR_ADDR: ":3090"